name: Flutter Deploy
description: Build and deploy Flutter apps via Fastlane

inputs:
  lane:
    description: 'ios deploy, android deploy, ios beta'
    required: true

runs:
  using: 'composite'
  steps:
    - run: |
        mkdir -p fastlane
        cp ${{ github.action_path }}/fastlane/Fastfile fastlane
        cp ${{ github.action_path }}/fastlane/Pluginfile fastlane
        cp ${{ github.action_path }}/Gemfile .
        bundle install
        doppler run -p deploy -c flutter -- bundle exec fastlane ${{ inputs.lane }}
      shell: bash
