PACKAGE_NAME = CredentialsManager::AppfileConfig.try_fetch_value(:package_name)

platform :android do
  lane :beta do
    sh("cd ../.. && flutter build appbundle --build-number=#{google_play_track_version_codes(track: 'internal').max + 1}")
    supply(
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      track: "internal",
      release_status: "completed",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
    slack
    telegram(text: "✅ *#{PACKAGE_NAME}* Android 베타 배포 완료")
  end

  lane :release do
    sh("cd ../.. && flutter build appbundle --build-number=#{google_play_track_version_codes.max + 1}")
    supply(aab: "../build/app/outputs/bundle/release/app-release.aab")
    slack
    telegram(text: "✅ *#{PACKAGE_NAME}* Android 릴리스 배포 완료")
  end
end

error do |lane, exception|
  slack(message: exception.message, success: false)
  telegram(text: "❌ *#{PACKAGE_NAME}* Android 배포 실패\n`#{exception.message}`")
end
