platform :android do
  lane :beta do
    sh("cd ../.. && flutter build appbundle --build-number=#{google_play_track_version_codes(track: 'internal').max + 1}")
    supply(
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      track: "internal",
      release_status: "completed",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  end

  lane :release do
    sh("cd ../.. && flutter build appbundle --build-number=#{google_play_track_version_codes.max + 1}")
    supply(aab: "../build/app/outputs/bundle/release/app-release.aab")
  end
end
