name: Flutter iOS Deploy
description: Build and deploy Flutter iOS apps via Fastlane

inputs:
  lane:
    description: 'deploy, beta'
    default: 'deploy'

runs:
  using: 'composite'
  steps:
    - env:
        BUNDLE_GEMFILE: ${{ github.action_path }}/Gemfile
      run: |
        bundle install
        mkdir -p ios/fastlane
        echo "import '${{ github.action_path }}/fastlane/Fastfile'" > ios/fastlane/Fastfile
        doppler run -p deploy -c flutter -- bundle exec fastlane ios ${{ inputs.lane }}
      shell: bash
