name: Deploy

on:
  workflow_call:
    inputs:
      lane:
        type: string
        default: deploy

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./android
        with:
          lane: ${{ inputs.lane }}

  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./ios
        with:
          lane: ${{ inputs.lane }}
